export const LEAD_SOURCE = {
  LEGACY_CONTACT_FORM: "legacy-contact-form",
  LANDING_CALCULATOR: "landing-calculator",
  OFFICE_MANUAL: "office-manual",
} as const;

export const LEAD_ACTIVITY = {
  CREATED: "LEAD_CREATED",
  ACCEPTED: "LEAD_ACCEPTED",
  CALLBACK_SCHEDULED: "CALLBACK_SCHEDULED",
  CALLBACK_UPDATED: "CALLBACK_UPDATED",
  EXPERT_CALL_REQUESTED: "EXPERT_CALL_REQUESTED",
  EXPERT_CALL_UPDATED: "EXPERT_CALL_UPDATED",
  EXPERT_CALL_CANCELLED: "EXPERT_CALL_CANCELLED",
  EXPERT_CALL_CONFIRMED: "EXPERT_CALL_CONFIRMED",
  EXPERT_CALL_DECLINED: "EXPERT_CALL_DECLINED",
  REJECTED: "LEAD_REJECTED",
} as const;

export const LEAD_PERMISSION = {
  READ_UNASSIGNED: "SALES_LEADS_READ_UNASSIGNED",
  CREATE: "SALES_LEADS_CREATE",
  ACCEPT: "SALES_LEADS_ACCEPT",
  MANAGE_OWN: "SALES_LEADS_MANAGE_OWN",
  READ_EXPERT_SLOTS: "SALES_EXPERTS_READ_SLOTS",
  READ_NOTIFICATIONS: "SALES_NOTIFICATIONS_READ",
  RESPOND_EXPERT_CALL: "EXPERT_LEAD_CALLS_RESPOND",
} as const;

export const SALES_MANAGER_ROLE = "SALES_MANAGER";

// Keep this below Express' default 100 KiB JSON parser limit so callers receive
// our domain error before the framework rejects the request body.
export const LEAD_SUBMISSION_MAX_BYTES = 96 * 1024;
