/** Типы событий пути студента (хранятся в `UserJourneyEvent.eventType`). */
export const USER_JOURNEY_EVENT = {
  REGISTRATION: "REGISTRATION",
  PROFILE_FILLED: "PROFILE_FILLED",
  PROGRAM_VIEWED: "PROGRAM_VIEWED",
  PROGRAM_SELECTED: "PROGRAM_SELECTED",
  DOCUMENT_UPLOADED: "DOCUMENT_UPLOADED",
  CONSULTATION_BOOKED: "CONSULTATION_BOOKED",
  CONTRACT_SIGNED: "CONTRACT_SIGNED",
  PAYMENT_COMPLETED: "PAYMENT_COMPLETED",
  MEETING_JOINED: "MEETING_JOINED",
} as const;

export type UserJourneyEventType = (typeof USER_JOURNEY_EVENT)[keyof typeof USER_JOURNEY_EVENT];

export const USER_JOURNEY_EVENT_TYPES = Object.values(USER_JOURNEY_EVENT);
